MVC_Project_R/Models/EstudianteViewModel.cs
using ADS_Project.Utils;
using System.ComponentModel.DataAnnotations;
namespace ADS_Project.Models
{
    public class EstudianteViewModel
    {
        [Display(Name ="ID")]
        public int idEstudiante { get; set; }

        [Required(ErrorMessage =Constants.REQUIRED_FIELD)]
        [StringLength(50,MinimumLength = 3,ErrorMessage ="La longitud del campo no debe ser mayor a 50 caracteres ni menor a 3 caracteres.")]
        [Display(Name = "Nombre")]
        public string nombresEstudiante { get; set; }

        [Required(ErrorMessage = Constants.REQUIRED_FIELD)]
        [StringLength(50, MinimumLength = 3, ErrorMessage = "La longitud del campo no debe ser mayor a 50 caracteres ni menor a 3 caracteres.")]
        [Display(Name = "Apellido")]
        public string apellidosEstudiante { get; set; }

        [Required(ErrorMessage = Constants.REQUIRED_FIELD)]
        [StringLength(12, MinimumLength = 12, ErrorMessage = "La longitud del campo de ser de 12 caracteres.")]
        [Display(Name = "Código")]
        public string codigoEstudiante { get; set; }

        [Required(ErrorMessage = Constants.REQUIRED_FIELD)]
        [StringLength(50, MinimumLength = 5, ErrorMessage = "La longitud del campo no debe ser mayor a 50 caracteres ni menor a 5 caracteres.")]
        [Display(Name = "Correo")]
        public string correoEstudiante { get; set; }

    }
}

MVC_Project_R/Controllers/EstudianteController.cs
using ADS_Project.Models;
using ADS_Project.Repository;
using ADS_Project.Utils;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ADS_Project.Controllers
{
    public class EstudianteController : Controller
    {
        private readonly IEstudianteRepository estudianteRepository;

        public EstudianteController(IEstudianteRepository estudianteRepository)
        {
            this.estudianteRepository = estudianteRepository;
        }

        [HttpGet]
        public IActionResult Index()
        {
            try
            {
                var item = estudianteRepository.obtenerEstudiantes();
                return View(item);
            }
            catch (Exception)
            {

                throw;
            }
        }

        [HttpGet]
        public IActionResult Form(int? idEstudiante, Operaciones operaciones)
        {
            try
            {
                var estudiante = new EstudianteViewModel();

                if (idEstudiante.HasValue)
                {
                    estudiante = estudianteRepository.obtenerEstudiantePorID(idEstudiante.Value);
                }

                //Indica el tipo de operacion que se esta realizando
                ViewData["Operaciones"] = operaciones;
                return View(estudiante);

            }
            catch (Exception)
            {

                throw;
            }
        }


        [HttpPost]
        public IActionResult Form(EstudianteViewModel estudianteViewModel)
        {
            try
            {
                if(estudianteViewModel.idEstudiante == 0) //En caso de insertar
                {

                    estudianteRepository.agregarEstudiante(estudianteViewModel);
                }
                else //En caso de actualizar
                {
                    estudianteRepository.actualizarEstudiante(estudianteViewModel.idEstudiante, estudianteViewModel);

                }

                return RedirectToAction("Index");
            }
            catch (Exception)
            {

                throw;
            }
        }

        [HttpPost]
        public IActionResult Delete(int idEstudiante)
        {
            try
            {
                estudianteRepository.eliminarEstudiante(idEstudiante);
            }
            catch (Exception)
            {

                throw;
            }

            return RedirectToAction("Index");
        }

    }
}

MVC_Project_R/Views/Estudiante/Form.cshtml
@model ADS_Project.Models.EstudianteViewModel

@{
    ViewData["Title"] = "Form";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Form</h1>

<h4>EstudianteViewModel</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <input type="hidden" id="operacion" value="@ViewData["Operaciones"]"/>
        <input type="hidden" id="_redirectURL" value="@Url.Action("Index","Estudiante")" />
        <form asp-action="Form">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <input asp-for="idEstudiante" class="form-control" type ="hidden"/>
            </div>
            <div class="form-group">
                <label asp-for="nombresEstudiante" class="control-label"></label>
                <input asp-for="nombresEstudiante" class="form-control" />
                <span asp-validation-for="nombresEstudiante" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="apellidosEstudiante" class="control-label"></label>
                <input asp-for="apellidosEstudiante" class="form-control" />
                <span asp-validation-for="apellidosEstudiante" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="codigoEstudiante" class="control-label"></label>
                <input asp-for="codigoEstudiante" class="form-control" />
                <span asp-validation-for="codigoEstudiante" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="correoEstudiante" class="control-label"></label>
                <input asp-for="correoEstudiante" class="form-control" />
                <span asp-validation-for="correoEstudiante" class="text-danger"></span>
            </div>
            
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Regresar</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}

    <script>
        $(document).ready(function () {
            // Cuando la operacion sobre el formulario es de lectura.
            if ($("#operacion").val() == "leer") {
                $("form").find("input,select").attr("disabled", true);
            }
        });
        $("from").addClass("Form-ajax");
        //activar ajax
        initAjaxForm();

    </script>

}

MVC_Project_R/Views/Estudiante/Index.cshtml
@model IEnumerable<ADS_Project.Models.EstudianteViewModel>
@using ADS_Project.Utils
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<div class="container">
    <div class="col-sm-12">
        <div class="row">
            <div class="col-sm-6">
                <h3>Estudiantes</h3>
            </div>
            <div class="col-sm-6">
                <a class="btn btn-success d-block" asp-action="Form" asp-route-operaciones="@Operaciones.agregar">Agregar Estudiante</a>
            </div>
        </div>

    </div>
    <div class="col-sm-12">
        @if (Model.Count() > 0)
        {
            <table class="table table-bordered table-striped" >
                <thead>
                    <tr>
                        <th>
                            @Html.DisplayNameFor(model => model.idEstudiante)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.nombresEstudiante)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.apellidosEstudiante)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.codigoEstudiante)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.correoEstudiante)
                        </th>
                        <th>
                            Acciones
                        </th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>
                                @Html.DisplayFor(modelItem => item.idEstudiante)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.nombresEstudiante)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.apellidosEstudiante)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.codigoEstudiante)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.correoEstudiante)
                            </td>
                            <td>
                                <a class="btn btn-primary" asp-route-idEstudiante="@item.idEstudiante" asp-action="Form" asp-route-operaciones="@Operaciones.modificar">Modificar</a>
                                <a class="btn btn-warning" asp-route-idEstudiante="@item.idEstudiante" asp-action="Form" asp-route-operaciones="@Operaciones.leer">Leer</a>
                                <a class="btn btn-danger eliminar" asp-route-idEstudiante="@item.idEstudiante" asp-action="Delete">Eliminar</a>
                            
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        }
        else
        {
            <h3 class="text-center">Lista Vacia.</h3>
        }
    </div>
</div>