MVC_Project_R/Models/GrupoViewModel.cs
using ADS_Project.Utils;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace MVC_Project_R.Models
{
    public class GrupoViewModel
    {
        [Display(Name = "ID")]
        public int idGrupo { get; set; }

        [Required(ErrorMessage = Constants.REQUIRED_FIELD)]
        [StringLength(50, MinimumLength = 3, ErrorMessage = "La longitud del campo no debe ser mayor a 50 caracteres ni menor a 3 caracteres.")]
        [Display(Name = "idCarrera")]
        public int idCarrera { get; set; }


        [Required(ErrorMessage = Constants.REQUIRED_FIELD)]
        [StringLength(50, MinimumLength = 3, ErrorMessage = "La longitud del campo no debe ser mayor a 50 caracteres ni menor a 3 caracteres.")]
        [Display(Name = "idMateria")]

        public int idMateria { get; set; }


        [Required(ErrorMessage = Constants.REQUIRED_FIELD)]
        [StringLength(50, MinimumLength = 3, ErrorMessage = "La longitud del campo no debe ser mayor a 50 caracteres ni menor a 3 caracteres.")]
        [Display(Name = "idProfesor")]
        public int idProfesor { get; set; }

        [Required(ErrorMessage = Constants.REQUIRED_FIELD)]
        [StringLength(50, MinimumLength = 3, ErrorMessage = "La longitud del campo no debe ser mayor a 50 caracteres ni menor a 3 caracteres.")]
        [Display(Name = "Ciclo")]

        public String Ciclo { get; set; }

        [Required(ErrorMessage = Constants.REQUIRED_FIELD)]
        [StringLength(50, MinimumLength = 3, ErrorMessage = "La longitud del campo no debe ser mayor a 50 caracteres ni menor a 3 caracteres.")]
        [Display(Name = "year")]

        public String year { get; set; }

    }
}

MVC_Project_R/Controllers/GrupoController.cs
using ADS_Project.Utils;
using Microsoft.AspNetCore.Mvc;
using MVC_Project_R.Models;
using MVC_Project_R.Repository;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MVC_Project_R.Controllers
{
    public class GrupoController : Controller
    {

        private readonly IGrupoRepository grupoRepository;

        public GrupoController(IGrupoRepository gruposRepository)
        {
            this.grupoRepository = gruposRepository;
        }

        [HttpGet]
        public IActionResult Index()
        {
            try
            {
                var item = grupoRepository.obtenerGrupo();
                return View(item);
            }
            catch (Exception)
            {

                throw;
            }
        }

        [HttpGet]
        public IActionResult Form(int? idGrupo, Operaciones operaciones)
        {
            try
            {
                var grupo = new GrupoViewModel();

                if (idGrupo.HasValue)
                {
                    grupo = grupoRepository.obtenerGrupoPorID(idGrupo.Value);
                }

                //Indica el tipo de operacion que se esta realizando
                ViewData["Operaciones"] = operaciones;
                return View(grupo);

            }
            catch (Exception)
            {

                throw;
            }
        }

        [HttpPost]
        public IActionResult Form(GrupoViewModel grupoViewModel)
        {
            try
            {
                if (grupoViewModel.idGrupo == 0) //En caso de insertar
                {

                    grupoRepository.agregarGrupo(grupoViewModel);
                }
                else //En caso de actualizar
                {
                    grupoRepository.actualizarGrupo(grupoViewModel.idGrupo,grupoViewModel);

                }

                return RedirectToAction("Index");
            }
            catch (Exception)
            {

                throw;
            }
        }


        [HttpPost]
        public IActionResult Delete(int idGrupo)
        {
            try
            {
                grupoRepository.eliminarGrupo(idGrupo);
            }
            catch (Exception)
            {

                throw;
            }

            return RedirectToAction("Index");
        }

    }
}

MVC_Project_R/Views/Grupo/Form.cshtml
@model MVC_Project_R.Models.GrupoViewModel

@{
    ViewData["Title"] = "Form";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Form</h1>

<h4>GrupoViewModel</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <input type="hidden" id="operacion" value="@ViewData["Operaciones"]" />
        <input type="hidden" id="_redirectURL" value="@Url.Action("Index","Grupo")" />
        <form asp-action="Form">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="idGrupo" class="control-label"></label>
                <input asp-for="idGrupo" class="form-control" />
                <span asp-validation-for="idGrupo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="idCarrera" class="control-label"></label>
                <input asp-for="idCarrera" class="form-control" />
                <span asp-validation-for="idCarrera" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="idMateria" class="control-label"></label>
                <input asp-for="idMateria" class="form-control" />
                <span asp-validation-for="idMateria" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="idProfesor" class="control-label"></label>
                <input asp-for="idProfesor" class="form-control" />
                <span asp-validation-for="idProfesor" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Ciclo" class="control-label"></label>
                <input asp-for="Ciclo" class="form-control" />
                <span asp-validation-for="Ciclo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="year" class="control-label"></label>
                <input asp-for="year" class="form-control" />
                <span asp-validation-for="year" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
<script>$(document).ready(function () {
            // Cuando la operacion sobre el formulario es de lectura.
            if ($("#operacion").val() == "leer") {
                $("form").find("input,select").attr("disabled", true);
            }
        });
        $("from").addClass("Form-ajax");
        //activar ajax
        initAjaxForm();</script>

}

MVC_Project_R/Views/Grupo/Index.cshtml
@model IEnumerable<MVC_Project_R.Models.GrupoViewModel>
@using ADS_Project.Utils
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Index</h1>

<div class="container">
    <div class="col-sm-12">
        <div class="row">
            <div class="col-sm-6">
                <h3>Grupo</h3>
            </div>
            <div class="col-sm-6">
                <a class="btn btn-success d-block" asp-action="Form" asp-route-operaciones="@Operaciones.agregar">Agregar Grupo</a>
            </div>
        </div>

    </div>
    <div class="col-sm-12">
        @if (Model.Count() > 0)
        {
            <table class="table table-bordered table-striped">
                <thead>
                    <tr>
                        <th>
                            @Html.DisplayNameFor(model => model.idGrupo)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.idCarrera)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.idMateria)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.idProfesor)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.Ciclo)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.year)
                        </th>
                        <th>
                            Acciones
                        </th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>
                                @Html.DisplayFor(modelItem => item.idGrupo)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.idCarrera)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.idMateria)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.idProfesor)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Ciclo)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.year)
                            </td>
                            <td>
                                <a class="btn btn-primary" asp-route-idGrupo="@item.idGrupo" asp-action="Form" asp-route-operaciones="@Operaciones.modificar">Modificar</a>
                                <a class="btn btn-warning" asp-route-idGrupo="@item.idGrupo" asp-action="Form" asp-route-operaciones="@Operaciones.leer">Leer</a>
                                <a class="btn btn-danger eliminar" asp-route-idGrupo="@item.idGrupo" asp-action="Delete">Eliminar</a>

                            </td>
                        </tr>
                    }
                </tbody>
            </table> }
        else
        {
            <h3 class="text-center">Lista Vacia.</h3>}
    </div>
</div>